apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mycsi-sc
provisioner: mycsi.jtthink.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycsi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # 不能超过10Gi，代码写死
  storageClassName: mycsi-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycsi-nginx
spec:
  selector:
    matchLabels:
      app: mycsi-nginx
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: mycsi-nginx
    spec:
      nodeName: vm-0-12-centos
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim: # 使用pvc挂载
            claimName: mycsi-pvc