apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfscsi-nginx
spec:
  selector:
    matchLabels:
      app: nfscsi-nginx
  template:
    metadata:
      labels:
        app: nfscsi-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.18-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:             # 挂载目录
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:    # 声明创建的pvc
            claimName: nfs-pvc